name: Build and Release rk322x Armbian Image

on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build & Release rk322x Image
    runs-on: ubuntu-latest
    timeout-minutes: 75

    env:
      BOARD: rk322x
      RELEASE: jammy
      BRANCH: current

    steps:
      - name: Checkout armbian/build
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          path: armbian-build
          submodules: true
          fetch-depth: 1

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential libncurses-dev flex bison libssl-dev \
            pv parted kmod e2fsprogs device-tree-compiler rsync u-boot-tools \
            libglib2.0-dev libpixman-1-dev qemu-system-arm
          sudo modprobe loop

      - name: Prepare cache directory
        run: |
          mkdir -p armbian-build/userpatches
          mkdir -p armbian-build/output

      - name: Build Armbian image for rk322x
        working-directory: armbian-build
        run: |
          ./compile.sh BOARD=${{ env.BOARD }} RELEASE=${{ env.RELEASE }} BRANCH=${{ env.BRANCH }} BUILD_MINIMAL=no BUILD_DESKTOP=no

      - name: Find image file
        id: find_image
        run: |
          IMAGE_PATH=$(find armbian-build/output/images/${{ env.BOARD }}/ -type f -name "*.img.xz")
          echo "image_path=$IMAGE_PATH" >> $GITHUB_ENV
          echo "File exists: $(test -f "$IMAGE_PATH" && echo "yes" || echo "no")"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: custom-rk322x-${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Image to Release
        if: env.image_path != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.image_path }}
          asset_name: armbian-${{ env.BOARD }}-${{ env.RELEASE }}-${{ env.BRANCH }}-${{ github.run_number }}.img.xz
          asset_content_type: application/octet-stream
